### ISSUE TITLE
Neo: Fade example does compile but no output

### ISSUE THREAD

**Issue by waltervl** [UDOOboard/arduino-board-package#2]
The (precompiled) fade example on the web-conf is working but when compiled from Arduino IDE on the Neo itself and web IDE it does not work. Tested with RC2 (and apparently also not working on RC1). Pinmode was out-commented.
See for more information the forum: http://www.udoo.org/forum/threads/fade-example-not-working-in-m4.3917/

**Comment by waltervl** [comment]
Can be closed: https://github.com/UDOOboard/arduino-board-package/commit/69a8c57

**Comment by ektor5** [comment]
Thanks @waltervl ;)
